### ISSUE TITLE
Please use git submodules

### ISSUE THREAD

**Issue by alex-tee** [sadko4u/lsp-dsp-lib#1]
thanks for this library!

I'm trying to package it on Guix, but no internet connection is allowed and it's messy to figure out how to pre-fetch everything. can you please add the required modules as git submodules, so that git clone-ing recursively would do the job without needing manual hacks?

**Comment by sadko4u** [comment]
Git submodules probably won't conform to the versioning model I'm using.
To pre-fetch everything, just use:
```
make config
make fetch
```

All dependencies will automatically be cloned into **modules** directory (and with desired versions).

**Comment by alex-tee** [comment]
> Git submodules probably won't conform to the versioning model I'm using.

ok, fair enough

> All dependencies will automatically be cloned into modules directory (and with desired versions).

I actually can't do this in Guix because internet connection is completely blocked after fetching the original git repo, so I need to pre-fetch the modules and move things accordingly. a bit inconvenient, but it's fine

**Comment by liamdiprose** [comment]
Thank you for your project @alex-tee! I'm currently packaging 1.0.0-beta4.5.1 for NixOS and here with the exact same issue as you. @sadko4u thank you for your project: I believe your project will be improved by pinning the exact commit-hash of each dependency you use, as per git submodules. You could adapt your makefile to update each dependency commit-hash to the version you're using automatically. As packagers, we just want to know the exact commit-hash you expect.

Please reconsider this decision.

**Comment by sadko4u** [comment]
I use branch names instead of commit hashes. That is more flexible for personally for me.
