### ISSUE TITLE
Add tarballs to releases

### ISSUE THREAD

**Issue by sadko4u** [sadko4u/lsp-dsp-lib#12]
For ditribution builders it would be a good feature to add tarballs with full source code tree to the release.
Need to add target which will generate release tarballs.

**Comment by sadko4u** [comment]
Pushed changes to **github-issue-12** branch

@alex-tee @fesari now you may issue:
```
make distsrc
```

This will generate `.build/lsp-dsp-lib-<version>-src.tar.gz` archive and symlink `.build/lsp-dsp-lib-src.tar.gz`.
Hope that will be good for you.

**Comment by sadko4u** [comment]
@alex-tee @fpesari

Merged changes into **devel** branch: f714f8952525886f8f37a88c73a0b8bb200e44f4

**Comment by sadko4u** [comment]
Released 0.5.8 version: 54d11845f04d9c5c958d0ac1d749fdc798c45f7c

**Comment by alex-tee** [comment]
awesome, thanks!
