### ISSUE TITLE
Static library is installed with executable permissions

### ISSUE THREAD

**Issue by fpesari** [sadko4u/lsp-dsp-lib#14]
Hello,

`make install` by default installs the .a file with executable permissions, when it should not (as a matter of fact, the openSUSE Build System refuses to build the package because of it).

**Comment by sadko4u** [comment]
Pushed changes to **github-issue-14** branch, please verify: 14b5ee434b2fc5052652aa02d3105469f6be78ab

**Comment by fpesari** [comment]
Yes, that one is fine.

(thanks for all the fast fixes btw :smile_cat:)

**Comment by sadko4u** [comment]
Merged into **devel** branch: 46d706108af88125b1d68d15a3a04fecf9a140de

**Comment by sadko4u** [comment]
Removed **github-issue-14** branch

**Comment by sadko4u** [comment]
Released 0.5.8 version: 54d11845f04d9c5c958d0ac1d749fdc798c45f7c
