### ISSUE TITLE
Library name in git tags causes redundant naming of tarball and top-level directory inside of it

### ISSUE THREAD

**Issue by fpesari** [sadko4u/lsp-dsp-lib#15]
Putting the program name in the git tags causes the tarballs to have a redundant file name, like `lsp-dsp-lib-lsp-dsp-lib-0.5.8.tar.gz` (try it yourself, click on this link -> https://github.com/sadko4u/lsp-dsp-lib/archive/lsp-dsp-lib-0.5.8.tar.gz and see what filename it proposes for the tarball and the directory inside). 

The convention for most packagers is {name}-{version}.tar.gz so this might throw off some automated tools.

To avoid that, you could tag just the version, like `0.5.8`.

**Comment by sadko4u** [comment]
It's not a tarball which I produce. This is automated github tarball and I have nothing to deal with it. It uses the tag name as the version which (propably) is wrong for our case.

**Comment by sadko4u** [comment]
I've uploaded the right tarball produced by `make distsrc` command: https://github.com/sadko4u/lsp-dsp-lib/releases/download/lsp-dsp-lib-0.5.8/lsp-dsp-lib-0.5.8-src.tar.gz

**Comment by fpesari** [comment]
Fine, just wanted to report it as I see many people using those Github /archive/ links to download packages :smile_cat: thank you for all!

**Comment by sadko4u** [comment]
I believe somewhere it is possible for github to remove the `lsp-dsp-lib-` prefix from tag name but I currently can not find the proper way how to do this.
