### ISSUE TITLE
underlinking issue on armv7hl arch

### ISSUE THREAD

**Issue by david-geiger** [sadko4u/lsp-dsp-lib#16]
Hi,

On Mageia Cauldron (linux) I have an underlinking issue only on armv7hl arch:

> /usr/bin/ld: /home/iurt/rpmbuild/BUILD/lsp-dsp-lib/.build/lsp-dsp-lib/lsp-dsp-lib.o: in function `lsp::dsp::init()':
/home/iurt/rpmbuild/BUILD/lsp-dsp-lib/src/main/dsp.cpp:85: undefined reference to `lsp::arm::dsp_init()'
collect2: error: ld returned 1 exit status

Attached full build log:
[build.armv7hl.0.20201220075510.log](https://github.com/sadko4u/lsp-dsp-lib/files/5720713/build.armv7hl.0.20201220075510.log)

**Comment by sadko4u** [comment]
Can you show the ```uname -a``` for the building machine?

**Comment by sadko4u** [comment]
It seems that configuration script considers the architecture being non-ARM but the C++ sees the corresponding macros and considers the architecture being ARM.

**Comment by sadko4u** [comment]
Also please attach the generated ```.config``` file from the build system.

**Comment by david-geiger** [comment]
I'll see if I can have this file and also for the uname -a in our online build system.

**Comment by david-geiger** [comment]
So ok in this attached build log there is the uname -a and uname -m call and also a cat .config.mk call:

[build.armv7hl.0.20201220120309.log](https://github.com/sadko4u/lsp-dsp-lib/files/5720883/build.armv7hl.0.20201220120309.log)

**Comment by sadko4u** [comment]
@david-geiger: the problem is that this ```uname``` isn't properly understood by the configuration script: ```armv8l armv8l armv8l```
Do you build for 32-bit ARM, right? I need to update the configuration script then.

**Comment by sadko4u** [comment]
And, another question: do you try to build 32-bit ARM binaries under 64-bit ARM architecture?

**Comment by david-geiger** [comment]
Yes we build for 32-bit ARM, and yes apparently we build 32-bit ARM binaries under a 64-bit ARM architecture.

**Comment by sadko4u** [comment]
@david-geiger then you should add ARCHITECTURE=armv7a to the build script to get the proper build.

**Comment by sadko4u** [comment]
In further releases I'll replace this option from 'armv7a' to just 'arm32' to not to make maintainers confused about the version of ARM architecture.

**Comment by david-geiger** [comment]
Adding ARCHITECTURE=armv7a work, thanks

**Comment by sadko4u** [comment]
Nice. I'll still keep the issue open until the configuration migrates from ```ARCHITECTURE=armv7a``` to ```ARCHITECTURE=arm32```.

**Comment by sadko4u** [comment]
Sill found some issues that ARCHITECTURE=arm32 produces armv6-related code which may be non-optimal for armv7 in some cases. I've kept ```ARCHITECTURE=armv7a``` option to set the proper architecture. By the other side, internally build scripts call the whole 32-bit ARM architecture as ```arm32```. This allows to avoid unnecessary branches in build scripts and simplify configuration.

Anyway, since the 0.5.13 release I think we should consider this issue to be closed.
